sudo: true
language: node_js
node_js:
  - '10'

branches:
  only:
    - /.*/

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc

install:
  - yarn install --production=false
  - pip install --user awscli

before_script:
  - yarn bootstrap
  - yarn link
  - git remote set-url origin https://${GT_ACCESS_TOKEN}@github.com/${TRAVIS_REPO_SLUG}

script:
  - yarn lint
  - yarn build
  - yarn test
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn deploy; fi'

deploy:
  - provider: script
    skip_cleanup: true
    script: yarn deploy
    on:
      branch: develop

notifications:
  email:
    on_failure: always
